# 错误边界

## 目录

[基本概念](#jump1)

[使用错误边界](#jump2)

[关于事件处理器](#jump3)

[](#jump4)

[](#jump5)

---	

<span id="jump1"></span>

## 基本概念

### 什么是错误边界

部分 UI 的 JavaScript 错误不应该导致整个应用崩溃，错误边界就是一种解决这一问题的组件

这种组件可以捕获并打印发生在其子组件树任何位置的 JavaScript 错误

并且，它会渲染出备用 UI

### 错误边界无法捕获以下场景中产生的错误

- 事件处理

- 异步代码（例如 setTimeout 或 requestAnimationFrame 回调函数）

- 服务端渲染

- 它自身抛出来的错误（并非它的子组件）

---

<span id="jump2"></span>

## 使用错误边界

### 生成错误边界

如果一个 class 组件中定义了 static getDerivedStateFromError() 或 componentDidCatch() 

这两个生命周期方法中的任意一个（或两个）时，那么它就变成一个错误边界

### 当抛出错误后

使用 static getDerivedStateFromError() 渲染备用 UI 

使用 componentDidCatch() 打印错误信息

### 实例

```javascript
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // 更新 state 使下一次渲染能够显示降级后的 UI
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // 你同样可以将错误日志上报给服务器
    logErrorToMyService(error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      // 你可以自定义降级后的 UI 并渲染
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children; 
  }
}
```

---

<span id="jump3"></span>

## 关于事件处理器

错误边界无法捕获事件处理器内部的错误

如果你需要在事件处理器内部捕获错误，使用普通的 JavaScript try / catch 语句：

```javascript
handleClick() {
  try {
    // 执行操作，如有错误则会抛出
  } catch (error) {
    this.setState({ error });
  }
}
```